amap/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from .views import index

urlpatterns = [
    url(r'^$', index),
    url('^logout/', auth_views.logout, {'next_page': '/'}),
    url('^', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^panier/', include('panier.urls', namespace='panier')),
    url(r'^search/', include('search.urls', namespace='search')),
]

panier/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^new_commande/(?P<userid>[0-9]+)$', views.new_commande, name='new-commande'),
    url(r'^edit_commande/(?P<commandeid>[0-9]+)$', views.edit_commande, name='edit-commande'),
    url(r'^del_commande/(?P<commandeid>[0-9]+)$', views.del_commande, name='del-commande'),
    url(r'^add_paiement/$', views.add_paiement, name='add-paiement'),
    url(r'^edit_paiement/(?P<paiementid>[0-9]+)$', views.edit_paiement, name='edit-paiement'),
    url(r'^del_paiement/$', views.del_paiement, name='del-paiement'),
    url(r'^index_paiement/$', views.index_paiement, name='index-paiement'),
    url(r'^add_livraison/$', views.add_livraison, name='add-livraison'),
    url(r'^edit_livraison/(?P<livraisonid>[0-9]+)$', views.edit_livraison, name='edit-livraison'),
    url(r'^del_livraison/$', views.del_livraison, name='del-livraison'),
    url(r'^index_livraison/$', views.index_livraison, name='index-livraison'),
    url(r'^add_credit/(?P<userid>[0-9]+)$', views.add_credit, name='add-credit'),
    url(r'^add_credit_note/(?P<userid>[0-9]+)$', views.add_credit_note, name='add-credit-note'),
    url(r'^edit_credit/(?P<creditid>[0-9]+)$', views.edit_credit, name='edit-credit'),
    url(r'^del_credit/(?P<creditid>[0-9]+)$', views.del_credit, name='del-credit'),
    url(r'^add_article/$', views.add_article, name='add-article'),
    url(r'^edit_article/(?P<articleid>[0-9]+)$', views.edit_article, name='edit-article'),
    url(r'^del_article/$', views.del_article, name='del-article'),
    url(r'^add_sac/(?P<userid>[0-9]+)$', views.add_sac, name='add-sac'),
    url(r'^del_sac/(?P<userid>[0-9]+)$', views.del_sac, name='del-sac'),
    url(r'^plusProcheLivraison/$', views.plusProcheLivraison, name='plusProcheLivraison'),
    url(r'^control/$', views.control, name='control'),
    url(r'^control/(?P<livraisonid>[0-9]+)$', views.control, name='control'),
    url(r'^index_article/$', views.index_article, name='index-article'),
    url(r'^history/(?P<object>paiement)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>livraison)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>credit)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>article)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>commande)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^$', views.index, name='index'),
]

users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^new_user/$', views.new_user, name='new-user'),
    url(r'^edit_info/(?P<userid>[0-9]+)$', views.edit_info, name='edit-info'),
    url(r'^state/(?P<userid>[0-9]+)$', views.state, name='state'),
    url(r'^password/(?P<userid>[0-9]+)$', views.password, name='password'),
    url(r'^add_right/(?P<userid>[0-9]+)$', views.add_right, name='add-right'),
    url(r'^del_right/$', views.del_right, name='del-right'),
    url(r'^add_listright/$', views.add_listright, name='add-listright'),
    url(r'^edit_listright/(?P<listrightid>[0-9]+)$', views.edit_listright, name='edit-listright'),
    url(r'^del_listright/$', views.del_listright, name='del-listright'),
    url(r'^profil/(?P<userid>[0-9]+)$', views.profil, name='profil'),
    url(r'^index_listright/$', views.index_listright, name='index-listright'),
    url(r'^mon_profil/$', views.mon_profil, name='mon-profil'),
    url(r'^process/(?P<token>[a-z0-9]{32})/$', views.process, name='process'),
    url(r'^reset_password/$', views.reset_password, name='reset-password'),
    url(r'^history/(?P<object>user)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>listright)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^$', views.index, name='index'),
]

users/forms.py
# -*- coding: utf-8 -*-


from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import User, get_admin_right


class PassForm(forms.Form):
    passwd1 = forms.CharField(label=u'Nouveau mot de passe', min_length=8, max_length=255, widget=forms.PasswordInput)
    passwd2 = forms.CharField(label=u'Saisir à nouveau le mot de passe', min_length=8, max_length=255, widget=forms.PasswordInput)

    def clean_passwd2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("passwd1")
        password2 = self.cleaned_data.get("passwd2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput, min_length=8, max_length=255)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput, min_length=8, max_length=255)
    is_admin = forms.BooleanField(label='is admin')

    class Meta:
        model = User
        fields = ('pseudo', 'name', 'surname', 'email')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.save()
        user.is_admin = self.cleaned_data.get("is_admin")
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()
    is_admin = forms.BooleanField(label='is admin', required=False)

    class Meta:
        model = User
        fields = ('pseudo', 'password', 'name', 'surname', 'email')

    def __init__(self, *args, **kwargs):
        super(UserChangeForm, self).__init__(*args, **kwargs)
        print("User is admin : %s" % kwargs['instance'].is_admin)
        self.initial['is_admin'] = kwargs['instance'].is_admin

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserChangeForm, self).save(commit=False)
        user.is_admin = self.cleaned_data.get("is_admin")
        if commit:
            user.save()
        return user

class ResetPasswordForm(forms.Form):
    pseudo = forms.CharField(label=u'Pseudo', max_length=255)
    email = forms.EmailField(max_length=255)

users/views.py
# coding: utf8
# App de gestion des users pour Amap
# Goulven Kermarec, Gabriel Détraz
# Gplv2
from django.shortcuts import render_to_response, get_object_or_404, render, redirect
from django.template.context_processors import csrf
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import Context, RequestContext, loader
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Max, ProtectedError
from django.db import IntegrityError
from django.core.mail import send_mail
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.db import transaction

from reversion import revisions as reversion
from users.models import User, Right, ListRight, Request
from users.models import DelRightForm, DelListRightForm, NewListRightForm
from users.models import EditInfoForm, BaseInfoForm, StateForm, RightForm, ListRightForm
from users.forms import PassForm, ResetPasswordForm
from reversion.models import Version


from panier.models import Commande, Credit

from amap.settings import REQ_EXPIRE_STR, EMAIL_FROM, ASSO_NAME, ASSO_EMAIL, SITE_NAME, PAGINATION_NUMBER


def form(ctx, template, request):
    c = ctx
    c.update(csrf(request))
    return render(
        request,
        template,
        c
    )

def password_change_action(u_form, user, request, req=False):
    """ Fonction qui effectue le changeemnt de mdp bdd"""
    user.set_password(u_form.cleaned_data['passwd1'])
    with transaction.atomic(), reversion.create_revision():
        user.save()
        reversion.set_comment("Réinitialisation du mot de passe")
    messages.success(request, "Le mot de passe a changé")
    if req:
        req.delete()
        return redirect("/")
    return redirect("/users/profil/" + str(user.id))

def reset_passwd_mail(req, request):
    t = loader.get_template('users/email_passwd_request')
    c = Context({
      'name': str(req.user.name) + ' ' + str(req.user.surname),
      'asso': ASSO_NAME,
      'asso_mail': ASSO_EMAIL,
      'site_name': SITE_NAME,
      'pseudo': str(req.user.pseudo),
      'url': request.build_absolute_uri(
       reverse('users:process', kwargs={'token': req.token})),
       'expire_in': REQ_EXPIRE_STR,
    })
    send_mail('Changement de mot de passe', t.render(c),
    EMAIL_FROM, [req.user.email], fail_silently=False)
    return

def new_user(request):
    user = EditInfoForm(request.POST or None)
    userpass = PassForm(request.POST or None)
    if user.is_valid() and userpass.is_valid():
        user = user.save(commit=False)
        with transaction.atomic(), reversion.create_revision():
            user.save()
            reversion.set_comment("Création")
        user.set_password(userpass.cleaned_data["passwd1"])
        return redirect("/users/profil/" + str(user.id))
    return form({'userform': user, 'userpass':userpass}, 'users/new_user.html', request)

@login_required
def edit_info(request, userid):
    try:
        user = User.objects.get(pk=userid)
    except User.DoesNotExist:
        messages.error(request, "Utilisateur inexistant")
        return redirect("/users/")
    if not request.user.has_perms(('bureau',)) and user != request.user:
        messages.error(request, "Vous ne pouvez pas modifier un autre user que vous sans droit bureau")
        return redirect("/users/profil/" + str(request.user.id))
    if not request.user.has_perms(('bureau',)):
        user = BaseInfoForm(request.POST or None, instance=user)
    else:
        user = EditInfoForm(request.POST or None, instance=user)
    if user.is_valid():
        with transaction.atomic(), reversion.create_revision():
            user.save()
            reversion.set_user(request.user)
            reversion.set_comment("Champs modifié(s) : %s" % ', '.join(field for field in user.changed_data))
        messages.success(request, "L'user a bien été modifié")
        return redirect("/users/profil/" + userid)
    return form({'userform': user}, 'users/user.html', request)

@login_required
@permission_required('bureau')
def state(request, userid):
    try:
        user = User.objects.get(pk=userid)
    except User.DoesNotExist:
        messages.error(request, "Utilisateur inexistant")
        return redirect("/users/")
    state = StateForm(request.POST or None, instance=user)
    if state.is_valid():
        with transaction.atomic(), reversion.create_revision():
            state.save()
            reversion.set_user(request.user)
            reversion.set_comment("Champs modifié(s) : %s" % ', '.join(field for field in state.changed_data))
        messages.success(request, "Etat changé avec succès")
        return redirect("/users/profil/" + userid)
    return form({'userform': state}, 'users/user.html', request)

@login_required
def password(request, userid):
    try:
        user = User.objects.get(pk=userid)
    except User.DoesNotExist:
        messages.error(request, "Utilisateur inexistant")
        return redirect("/users/")
    if not request.user.has_perms(('bureau',)) and user != request.user:
        messages.error(request, "Vous ne pouvez pas modifier un autre user que vous sans droit bureau")
        return redirect("/users/profil/" + str(request.user.id))
    if not request.user.has_perms(('bureau',)) and user != request.user and Right.objects.filter(user=user):
        messages.error(request, "Il faut les droits bureau pour modifier le mot de passe d'un membre actif")
        return redirect("/users/profil/" + str(request.user.id))
    u_form = PassForm(request.POST or None)
    if u_form.is_valid():
        return password_change_action(u_form, user, request)
    return form({'userform': u_form}, 'users/user.html', request)

@login_required
@permission_required('bureau')
def del_right(request):
    user_right_list = DelRightForm(request.POST or None)
    if user_right_list.is_valid():
        right_del = user_right_list.cleaned_data['rights']
        right_del.delete()
        messages.success(request, "Droit retiré avec succès")
        return redirect("/users/")
    return form({'userform': user_right_list}, 'users/user.html', request)

@login_required
@permission_required('bureau')
def add_right(request, userid):
    try:
        user = User.objects.get(pk=userid)
    except User.DoesNotExist:
        messages.error(request, "Utilisateur inexistant")
        return redirect("/users/")
    right = RightForm(request.POST or None)
    if right.is_valid():
        right = right.save(commit=False)
        right.user = user
        try:
            right.save()
            messages.success(request, "Droit ajouté")
        except IntegrityError:
            pass
        return redirect("/users/profil/" + userid)
    return form({'userform': right}, 'users/user.html', request)

@login_required
@permission_required('bureau')
def add_listright(request):
    listright = NewListRightForm(request.POST or None)
    if listright.is_valid():
        with transaction.atomic(), reversion.create_revision():
            listright.save()
            reversion.set_user(request.user)
            reversion.set_comment("Création")
        messages.success(request, "Le droit/groupe a été ajouté")
        return redirect("/users/index_listright/")
    return form({'userform': listright}, 'users/user.html', request)

@login_required
@permission_required('bureau')
def edit_listright(request, listrightid):
    try:
        listright_instance = ListRight.objects.get(pk=listrightid)
    except ListRight.DoesNotExist:
        messages.error(request, u"Entrée inexistante" )
        return redirect("/users/")
    listright = ListRightForm(request.POST or None, instance=listright_instance)
    if listright.is_valid():
        with transaction.atomic(), reversion.create_revision():
            listright.save()
            reversion.set_user(request.user)
            reversion.set_comment("Champs modifié(s) : %s" % ', '.join(field for field in listright.changed_data))
        messages.success(request, "Droit modifié")
        return redirect("/users/index_listright/")
    return form({'userform': listright}, 'users/user.html', request)

@login_required
@permission_required('bureau')
def del_listright(request):
    listright = DelListRightForm(request.POST or None)
    if listright.is_valid():
        listright_dels = listright.cleaned_data['listrights']
        for listright_del in listright_dels:
            try:
                with transaction.atomic(), reversion.create_revision():
                    listright_del.delete()
                    reversion.set_comment("Destruction")
                messages.success(request, "Le droit/groupe a été supprimé")
            except ProtectedError:
                messages.error(
                    request,
                    "Le droit %s est affecté à au moins un user, \
                        vous ne pouvez pas le supprimer" % listright_del)
        return redirect("/users/index_listright/")
    return form({'userform': listright}, 'users/user.html', request)

@login_required
@permission_required('bureau')
def index(request):
    users_list = User.objects.order_by('surname')
    paginator = Paginator(users_list, PAGINATION_NUMBER)
    page = request.GET.get('page')
    try:
        users_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        users_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        users_list = paginator.page(paginator.num_pages)
    return render(request, 'users/index.html', {'users_list': users_list})

@login_required
@permission_required('bureau')
def index_listright(request):
    listright_list = ListRight.objects.order_by('listright')
    return render(request, 'users/index_listright.html', {'listright_list':listright_list})

@login_required
def history(request, object, id):

users/templates/users/aff_listright.html
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Droit</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        {% for listright in listright_list %}
        <tr>
            <td>{{ listright.listright }}</td>
            <td><a class="btn btn-primary btn-sm" role="button" href="{% url 'users:edit-listright' listright.id %}"><i class="glyphicon glyphicon-pushpin"></i> Editer</a></td>
            <td><a class="btn btn-info btn-sm" role="button" href="{% url 'users:history' 'listright' listright.id %}"><i class="glyphicon glyphicon-repeat"></i> Historique</a></td>
        </tr>
        {% endfor %}
    </table>

users/templates/users/aff_users.html
 {% if users_list.paginator %}
 <ul class="pagination nav navbar-nav">
    {% if users_list.has_previous %}
            <li><a href="?page={{ users_list.previous_page_number }}">Suivants</a></li>
    {% endif %}
    {% for page in users_list.paginator.page_range %}
        <li class="{% if users_list.number == page  %}active{% endif %}"><a href="?page={{page }}">{{ page }}</a></li>
    {% endfor %}

    {% if users_list.has_next %}
        <li> <a href="?page={{ users_list.next_page_number }}">Précédents</a></li>
    {% endif %}
 </ul>
 {% endif %}

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Profil</th>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Pseudo</th>
                <th>Statut</th>
                <th>Telephone</th>
                <th>Mail</th>
            </tr>
        </thead>
        {% for user in users_list %}
        <tr>
            <td><a href="{% url "users:profil" user.id%}" class="btn btn-primary btn-sm" role="button"><i class="glyphicon glyphicon-user"></i></a>
            </td>
            <td>{{ user.name }}</td>
            <td>{{ user.surname }}</td>
            <td>{{ user.pseudo }}</td>
            {% if user.state == 0 %}
            <td><font color="green">Actif</font></td>
            {% elif user.state == 1 %}
            <td><font color="red">Désactivé</font></td>
            {% else %}
            <td><font color="orange">Archivé</font></td>
            {% endif %}
            <td>{{ user.telephone }}</td>
            <td>{{ user.email }}</td>
        </tr>
        {% endfor %}
    </table>

users/templates/users/index.html
{% extends "users/sidebar.html" %}
{% load bootstrap3 %}

{% block title %}Utilisateurs{% endblock %}

{% block content %}
  <h2>Adhérents</h2>
  {%  include "users/aff_users.html" with  users_list=users_list %}
  <br />
  <br />
  <br />
{% endblock %}

users/templates/users/index_listright.html
{% extends "users/sidebar.html" %}
{% load bootstrap3 %}

{% block title %}Utilisateurs{% endblock %}

{% block content %}
  <h2>Liste des droits</h2>
  <a class="btn btn-primary btn-sm" role="button" href="{% url 'users:add-listright'  %}"><i class="glyphicon glyphicon-plus"></i> Ajouter un droit ou groupe</a>
  <a class="btn btn-danger btn-sm" role="button" href="{% url 'users:del-listright'  %}"><i class="glyphicon glyphicon-trash"></i> Supprimer un ou plusieurs droits/groupes</a>
  {%  include "users/aff_listright.html" with  listright_list=listright_list %}
  <br />
  <br />
  <br />
{% endblock %}

users/templates/users/new_user.html
{% extends "users/sidebar.html" %}
{% load bootstrap3 %}

{% block title %}Création et modification d'utilisateur{% endblock %}

{% block content %}
{% bootstrap_form_errors userform %}
{% bootstrap_form_errors userpass %}


<form class="form" method="post">
    {% csrf_token %}
    {% bootstrap_form userform %}
    {% bootstrap_form userpass %}
    {% bootstrap_button "Créer ou modifier" button_type="submit" icon="star" %}
</form>
  <br />
  <br />
  <br />
{% endblock %}

users/templates/users/profil.html
{% extends "users/sidebar.html" %}
{% load bootstrap3 %}

{% block title %}Profil{% endblock %}

{% block content %}
    <h2>Adhérent</h2>
    <a class="btn btn-primary btn-sm" role="button" href="{% url 'users:edit-info' user.id %}"><i class="glyphicon glyphicon-edit"></i> Editer</a>  
    <a class="btn btn-primary btn-sm" role="button" href="{% url 'users:password' user.id %}"><i class="glyphicon glyphicon-lock"></i> Changer le mot de passe</a>  
    {% if is_bureau %}<a class="btn btn-primary btn-sm" role="button" href="{% url 'users:state' user.id %}"><i class="glyphicon glyphicon-flash"></i> Changer le statut</a>
    <a class="btn btn-primary btn-sm" role="button" href="{% url 'users:add-right' user.id %}"><i class="glyphicon glyphicon-ok"></i> Ajouter un droit</a>{% endif %}
    <a class="btn btn-info btn-sm" role="button" href="{% url 'users:history' 'user' user.id %}"><i class="glyphicon glyphicon-repeat"></i> Historique</a>
    <br />
    <br />
    <table class="table table-striped">
        <tr>
            <th>Prénom</th>
            <td>{{ user.name }}</td>
            <th>Nom</th>
            <td>{{ user.surname }}</td>
        </tr>
        <tr>
            <th>Pseudo</th>
            <td>{{ user.pseudo }}</td>
            <th>E-mail</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>Telephone</th>
            <td>{{ user.telephone }}</td>
            <th>Solde</th>
            <td>{{ user.solde }} €</td>
        </tr>
        <tr>
            <th>Date d'inscription</th>
            <td>{{ user.registered }}</td>
            <th>ENS</th>
            {% if user.is_ens %}
            <td><font color="green">Oui</font></td>
            {% else %}
            <td><font color="red">Non</font></td>
            {% endif %}
        </tr>
        <tr>
            <th>Statut</th>
            {% if user.state == 0 %}
            <td><font color="green">Actif</font></td>
            {% elif user.state == 1 %}
            <td><font color="red">Désactivé</font></td>
            {% else %}
            <td><font color="orange">Archivé</font></td>
            {% endif %}
            <th>Droits</th>
            {% if list_droits %}
            <td>{% for droit in list_droits %}{{ droit.right }}{% if list_droits|length != forloop.counter %}  - {% endif %} {% endfor %}</td>
            {% else %}
            <td>Aucun</td>
            {% endif %}
        </tr>
        <tr>
            <th>Sac consigné</th>
            <td>{{ user.sac_consignes }}</td>
            <th>Commentaire</th>
            <td>{{ user.comment }}</td>
        </tr>
    </table>

<h2>Commandes et crédits</h2>
{% if is_bureau %}<a class="btn btn-primary btn-sm" role="button" href="{% url 'panier:add-credit' user.id %}"><i class="glyphicon glyphicon-piggy-bank"></i> Enregistrer un crédit</a>{% endif %}
<a class="btn btn-primary btn-sm" role="button" href="{% url 'panier:new-commande' user.id %}"><i class="glyphicon glyphicon-shopping-cart"></i> Nouvelle commande</a>
<a class="btn btn-primary btn-sm" role="button" href="{% url 'panier:add-credit-note' user.id %}"><i class="glyphicon glyphicon-piggy-bank"></i> Crédit par note Kfet</a>
{% if is_bureau %}<a class="btn btn-primary btn-sm" role="button" href="{% url 'panier:add-sac' user.id %}"><i class="glyphicon glyphicon-plus"></i> Ajouter un sac consigné</a>
<a class="btn btn-primary btn-sm" role="button" href="{% url 'panier:del-sac' user.id %}"><i class="glyphicon glyphicon-minus"></i> Retirer un sac consigné</a>{% endif %}
<br/>

{%  include "panier/aff_paniers.html" %}
<br/>
<br/>
<br/>
{% endblock %}

users/templates/users/sidebar.html
{% extends "base.html" %}

{% block sidebar %}
    {% if is_bureau %}
        <a class="list-group-item list-group-item-success" href="{% url "users:new-user" %}">
            <i class="glyphicon glyphicon-plus"></i>
            Créer un adhérent
        </a>
        <a class="list-group-item list-group-item-info" href="{% url "users:index" %}">
            <i class="glyphicon glyphicon-list"></i>
            Adhérents
        </a>
        <a class="list-group-item list-group-item-info" href="{% url "users:index-listright" %}">
            <i class="glyphicon glyphicon-list"></i>
            Droits
        </a>
        <a class="list-group-item list-group-item-danger" href="{% url "users:del-right" %}">
            <i class="glyphicon glyphicon-trash"></i>
            Retirer un droit
        </a>
    {% endif %}
{% endblock %}

users/templates/users/user.html
{% extends "users/sidebar.html" %}
{% load bootstrap3 %}

{% block title %}Création et modification d'utilisateur{% endblock %}

{% block content %}
{% bootstrap_form_errors userform %}

<form class="form" method="post">
    {% csrf_token %}
    {% bootstrap_form userform %}
    {% bootstrap_button "Créer ou modifier" button_type="submit" icon="star" %}
</form>
  <br />
  <br />
  <br />
{% endblock %}