amap/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from .views import index

urlpatterns = [
    url(r'^$', index),
    url('^logout/', auth_views.logout, {'next_page': '/'}),
    url('^', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^panier/', include('panier.urls', namespace='panier')),
    url(r'^search/', include('search.urls', namespace='search')),
]

search/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.search, name='search'),
    url(r'^avance/$', views.searchp, name='searchp'),
]

users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^new_user/$', views.new_user, name='new-user'),
    url(r'^edit_info/(?P<userid>[0-9]+)$', views.edit_info, name='edit-info'),
    url(r'^state/(?P<userid>[0-9]+)$', views.state, name='state'),
    url(r'^password/(?P<userid>[0-9]+)$', views.password, name='password'),
    url(r'^add_right/(?P<userid>[0-9]+)$', views.add_right, name='add-right'),
    url(r'^del_right/$', views.del_right, name='del-right'),
    url(r'^add_listright/$', views.add_listright, name='add-listright'),
    url(r'^edit_listright/(?P<listrightid>[0-9]+)$', views.edit_listright, name='edit-listright'),
    url(r'^del_listright/$', views.del_listright, name='del-listright'),
    url(r'^profil/(?P<userid>[0-9]+)$', views.profil, name='profil'),
    url(r'^index_listright/$', views.index_listright, name='index-listright'),
    url(r'^mon_profil/$', views.mon_profil, name='mon-profil'),
    url(r'^process/(?P<token>[a-z0-9]{32})/$', views.process, name='process'),
    url(r'^reset_password/$', views.reset_password, name='reset-password'),
    url(r'^history/(?P<object>user)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>listright)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^$', views.index, name='index'),
]

templates/base.html
{% load staticfiles %}

{# Load the tag library #}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="fr">
    <head>
        {# Load CSS and JavaScript #}
        {% bootstrap_css %}
        <link rel="stylesheet" href="{% static "/css/base.css" %}">

        {% bootstrap_javascript %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{{ site_name }} : {% block title %}Accueil{% endblock %}</title>
    </head>

    <body>
        <div id="wrap">
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/">{{ site_name }}</a>
                    </div>
                    <div class="collapse navbar-collapse" id="myNavbar">
                        <ul class="nav navbar-nav">
                            <li><a href="{% url "users:mon-profil" %}">Mon profil</a></li>
                            <li><a href="{% url "panier:index" %}">Les commandes</a></li>
                            {% if is_bureau %}
                            <li><a href="{% url "users:index" %}">Gérer les utilisateurs</a></li>
                            {% endif %}
                        </ul>
                        <div class="col-sm-3 col-md-3 navbar-right">
                            <form action="{% url "search:search"%}"  method="POST" class="navbar-form" role="search">
                                {% csrf_token %}
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search" name="search_field" id="search-term">
                                    <div class="input-group-btn">
                                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                        <a href="{% url "search:searchp" %}" class="btn btn-default" role="button"><i class="glyphicon glyphicon-plus"></i></a>
                                   </div>
                                </div>
                            </form>
                        </div>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                {% if request.user.is_authenticated %}
                                <a href="{% url 'logout' %}">
                                    <span class="glyphicon glyphicon-log-out"></span> Logout
                                </a>
                                {% else %}
                                <a href="{% url 'login' %}">
                                    <span class="glyphicon glyphicon-log-in"></span> Login
                                </a>
                                {% endif %}
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            <div id="main" class="container-fluid text-center">
                <div class="row content">
                    <div class="col-sm-2 sidenav">
                        {% block sidebar %}
                        {% endblock %}
                    </div>
                    <div class="col-sm-8 text-left">
                        {# Display django.contrib.messages as Bootstrap alerts #}
                        {% bootstrap_messages %}

                        <hr>

                        {% block content %}{% endblock %}
                    </div>
                    <div class="col-sm-2 sidenav">
                        <div class="panel panel-default">
                            {% if request_user.is_authenticated %}
                            <div class="panel-heading">
                                <h4>{{ request_user.name }} {{ request_user.surname }}</h4>
                            </div>
                            <table class="table">
                                <tr>
                                    <th scope="row">Pseudo</th>
                                    <td class="text-right">{{ request_user.pseudo }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Solde</th>
                                    <td class="text-right">{{ request_user.solde }}</td>
                                </tr>
                                {% for droit in list_droits %}
                                <tr>
			            <th scope="row">Droits</th>
                                    <td class="text-right">{{ droit.right }}</td>
                                </tr>
                                {% endfor %}
                            </table>
                            <div class="list-group">
                                <a class="list-group-item list-group-item-info" role="button"href="{% url "users:mon-profil" %}">
                                    <i class="glyphicon glyphicon-user"></i>
                                    Voir mon profil
                                </a>
                            </div>
                            {% else %}
                            <p>Vous n'êtes pas authentifié</p>
                            {% endif %}
                        </div>
                        <center><p style="color:#C6C1C1;font-size: 70%;">En cas d'extrêmement rarissime soucis technique de notre côté rappelez vous que l'erreur est humaine et à NormalSoup', nous valorisons l'humain avant tout ! Et souquez les artimuses !</p></center>
                    </div>
                </div>
            </div>
        </div>

        <footer class="navbar">
            <div class="containerfluid text-center">
                <p>Amap 2017 - Gabriel Détraz, Arthur Grisel-Davy</p>
            </div>
        </footer>


        {# Read the documentation for more information #}
    </body>
</html>