amap/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from .views import index

urlpatterns = [
    url(r'^$', index),
    url('^logout/', auth_views.logout, {'next_page': '/'}),
    url('^', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^panier/', include('panier.urls', namespace='panier')),
    url(r'^search/', include('search.urls', namespace='search')),
]

panier/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^new_commande/(?P<userid>[0-9]+)$', views.new_commande, name='new-commande'),
    url(r'^edit_commande/(?P<commandeid>[0-9]+)$', views.edit_commande, name='edit-commande'),
    url(r'^del_commande/(?P<commandeid>[0-9]+)$', views.del_commande, name='del-commande'),
    url(r'^add_paiement/$', views.add_paiement, name='add-paiement'),
    url(r'^edit_paiement/(?P<paiementid>[0-9]+)$', views.edit_paiement, name='edit-paiement'),
    url(r'^del_paiement/$', views.del_paiement, name='del-paiement'),
    url(r'^index_paiement/$', views.index_paiement, name='index-paiement'),
    url(r'^add_livraison/$', views.add_livraison, name='add-livraison'),
    url(r'^edit_livraison/(?P<livraisonid>[0-9]+)$', views.edit_livraison, name='edit-livraison'),
    url(r'^del_livraison/$', views.del_livraison, name='del-livraison'),
    url(r'^index_livraison/$', views.index_livraison, name='index-livraison'),
    url(r'^add_credit/(?P<userid>[0-9]+)$', views.add_credit, name='add-credit'),
    url(r'^add_credit_note/(?P<userid>[0-9]+)$', views.add_credit_note, name='add-credit-note'),
    url(r'^edit_credit/(?P<creditid>[0-9]+)$', views.edit_credit, name='edit-credit'),
    url(r'^del_credit/(?P<creditid>[0-9]+)$', views.del_credit, name='del-credit'),
    url(r'^add_article/$', views.add_article, name='add-article'),
    url(r'^edit_article/(?P<articleid>[0-9]+)$', views.edit_article, name='edit-article'),
    url(r'^del_article/$', views.del_article, name='del-article'),
    url(r'^add_sac/(?P<userid>[0-9]+)$', views.add_sac, name='add-sac'),
    url(r'^del_sac/(?P<userid>[0-9]+)$', views.del_sac, name='del-sac'),
    url(r'^plusProcheLivraison/$', views.plusProcheLivraison, name='plusProcheLivraison'),
    url(r'^control/$', views.control, name='control'),
    url(r'^control/(?P<livraisonid>[0-9]+)$', views.control, name='control'),
    url(r'^index_article/$', views.index_article, name='index-article'),
    url(r'^history/(?P<object>paiement)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>livraison)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>credit)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>article)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>commande)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^$', views.index, name='index'),
]

users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^new_user/$', views.new_user, name='new-user'),
    url(r'^edit_info/(?P<userid>[0-9]+)$', views.edit_info, name='edit-info'),
    url(r'^state/(?P<userid>[0-9]+)$', views.state, name='state'),
    url(r'^password/(?P<userid>[0-9]+)$', views.password, name='password'),
    url(r'^add_right/(?P<userid>[0-9]+)$', views.add_right, name='add-right'),
    url(r'^del_right/$', views.del_right, name='del-right'),
    url(r'^add_listright/$', views.add_listright, name='add-listright'),
    url(r'^edit_listright/(?P<listrightid>[0-9]+)$', views.edit_listright, name='edit-listright'),
    url(r'^del_listright/$', views.del_listright, name='del-listright'),
    url(r'^profil/(?P<userid>[0-9]+)$', views.profil, name='profil'),
    url(r'^index_listright/$', views.index_listright, name='index-listright'),
    url(r'^mon_profil/$', views.mon_profil, name='mon-profil'),
    url(r'^process/(?P<token>[a-z0-9]{32})/$', views.process, name='process'),
    url(r'^reset_password/$', views.reset_password, name='reset-password'),
    url(r'^history/(?P<object>user)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>listright)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^$', views.index, name='index'),
]

panier/models.py
# coding: utf8
from django.db import models

from django.forms import ModelForm, Form
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

from django.core.validators import MaxValueValidator, MinValueValidator

class Panier(models.Model):
    prix = models.DecimalField(max_digits=5, decimal_places=2)
    nom = models.CharField(max_length=255)
    coefficient_panier = models.DecimalField(max_digits=3, decimal_places=2, null=True)

    def __str__(self):
        return self.nom

class Commande(models.Model):
    user = models.ForeignKey('users.User', on_delete=models.PROTECT)
    nom = models.CharField(max_length=255)
    coefficient_panier = models.DecimalField(max_digits=3, decimal_places=2, null=True)
    quantite = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    prix_unitaire = models.DecimalField(max_digits=5, decimal_places=2)
    livre = models.BooleanField(default=False)
    date = models.ForeignKey('Livraison', on_delete=models.PROTECT)

    def prix(self):
        return self.prix_unitaire*self.quantite

class Credit(models.Model):
    user = models.ForeignKey('users.User', on_delete=models.PROTECT)
    montant = models.DecimalField(max_digits=5, decimal_places=2)
    moyen = models.ForeignKey('Paiement', on_delete=models.PROTECT)
    validite = models.BooleanField(default=True)

    def __str__(self):
        return str(self.montant) + "€ pour " +  str(self.user)

class Paiement(models.Model):
    moyen = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.moyen

class Livraison(models.Model):
    date = models.DateTimeField(help_text='%d/%m/%y %H:%M:%S')
    date_modif = models.DateTimeField(help_text='%d/%m/%y %H:%M:%S')

    def __str__(self):
        return str(self.date)

panier/views.py
# coding: utf8
# App de gestion des paniers pour Amap
# Gabriel Détraz
# Gplv2

from django.shortcuts import render_to_response, get_object_or_404, render, redirect
from django.template.context_processors import csrf
from django.template import Context, RequestContext, loader
from django.contrib import messages
from django.db import IntegrityError
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponseRedirect

from django.db import transaction
from reversion import revisions as reversion
from .models import Panier, Paiement, Commande, Credit, Livraison
from .forms import PaiementForm, CreditForm, CreditFullForm, CreditNoteForm, DelPaiementForm, LivraisonForm, SelectOneLivraisonForm, SelectLivraisonForm
from .forms import PanierForm, DelPanierForm, SelectArticleForm, FullEditCommandeForm, BaseEditCommandeForm, NewCommandeForm
from django.forms import modelformset_factory, formset_factory
from reversion.models import Version
from fractions import Fraction

from amap.settings import note_server, note_port, note_id

from users.views import User
from django.utils import timezone

from amap.settings import MINIMUM_LEVEL, PAGINATION_LARGE_NUMBER, PAGINATION_NUMBER

from .note import connect, login, don

def form(ctx, template, request):
    c = ctx
    c.update(csrf(request))
    return render(
        request,
        template,
        c
    )

@login_required
def new_commande(request, userid):
    try:
        user = User.objects.get(pk=userid)
    except User.DoesNotExist:
        messages.error(request, u"Utilisateur inexistant" )
        return redirect("/panier/")
    if not request.user.has_perms(('bureau',)) and user != request.user:
        messages.error(request, "Vous ne pouvez pas commander pour quelqu'un d'autre !")
        return redirect("/users/profil/" + str(request.user.id))
    commande = Commande(user=user)
    commande_form = NewCommandeForm(request.POST or None, instance=commande, is_bureau=request.user.has_perms(('bureau',)))
    article_form = SelectArticleForm(request.POST or None)
    if commande_form.is_valid() and article_form.is_valid():
        commande = commande_form.save(commit=False)
        commande.prix_unitaire = article_form.cleaned_data['article'].prix
        commande.nom = article_form.cleaned_data['article'].nom
        commande.coefficient_panier = article_form.cleaned_data['article'].coefficient_panier
        # Si non surdroits, check solde et date
        if not request.user.has_perms(('bureau',)):
            if timezone.now() > commande.date.date_modif:
                messages.error(request, "Vous ne pouvez plus passer commande, livraison proche")
                return redirect("/users/profil/" + str(request.user.id))
            if user.solde() - commande.prix() < MINIMUM_LEVEL:
                messages.error(request, "Solde insuffisant pour effectuer l'operation")
                return redirect("/users/profil/" + userid)
        with transaction.atomic(), reversion.create_revision():
            commande.save()
            reversion.set_user(request.user)
            reversion.set_comment("Création")
        messages.success(request, "La commande est enregistree")
        return redirect("/users/profil/" + userid)
    return form({'article_form': article_form, 'commande_form': commande_form}, 'panier/new_commande.html', request)

@login_required
def edit_commande(request, commandeid):
    try:
        commande_instance = Commande.objects.get(pk=commandeid)
    except Commande.DoesNotExist:
        messages.error(request, u"Entrée inexistante" )
        return redirect("/panier/")
    if not request.user.has_perms(('bureau',)) and commande_instance.user != request.user:
        messages.error(request, "Vous ne pouvez pas commander pour quelqu'un d'autre !")
        return redirect("/users/profil/" + str(request.user.id))
    if request.user.has_perms(('bureau',)):
        commande = FullEditCommandeForm(request.POST or None, instance=commande_instance)
    else:
        if timezone.now() > commande_instance.date.date_modif:
            messages.error(request, "Vous ne pouvez plus modifier la commande, livraison proche")
            return redirect("/users/profil/" + str(request.user.id))
        commande = BaseEditCommandeForm(request.POST or None, instance=commande_instance)
    if commande.is_valid():
        new_commande = commande.save(commit=False)
        if commande_instance.user.solde() - new_commande.prix() < MINIMUM_LEVEL and not request.user.has_perms(('bureau',)):
            messages.error(request, "Solde insuffisant pour effectuer l'operation")
            return redirect("/panier/")
        with transaction.atomic(), reversion.create_revision():
            commande.save()
            reversion.set_user(request.user)
            reversion.set_comment("Champs modifié(s) : %s" % ', '.join(field for field in commande.changed_data))
        messages.success(request, "Commande modifiée")
        #return redirect("/panier/")
        return HttpResponseRedirect("")
    return form({'panierform': commande}, 'panier/panier.html', request)

@login_required
def del_commande(request, commandeid):
    try:
        commande = Commande.objects.get(pk=commandeid)
    except Commande.DoesNotExist:
        messages.error(request, u"Credit inexistant" )
        return redirect("/panier/")
    if not request.user.has_perms(('bureau',)) and commande.user != request.user:
        messages.error(request, "Vous ne pouvez pas commander pour quelqu'un d'autre !")
        return redirect("/users/profil/" + str(request.user.id))
    if timezone.now() > commande.date.date_modif and not request.user.has_perms(('bureau',)):
        messages.error(request, "Vous ne pouvez plus supprimer la commande, livraison proche")
        return redirect("/users/profil/" + str(request.user.id))
    if request.method == "POST":
        with transaction.atomic(), reversion.create_revision():
            commande.delete()
            reversion.set_user(request.user)
        messages.success(request, "La commande a été détruite")
        return redirect("/panier/")
    return form({'objet': commande, 'objet_name': 'commande'}, 'panier/delete.html', request)

@login_required
@permission_required('bureau')
def add_livraison(request):
    livraison = LivraisonForm(request.POST or None)
    if livraison.is_valid():
        with transaction.atomic(), reversion.create_revision():
            livraison.save()
            reversion.set_user(request.user)
            reversion.set_comment("Creation")
        messages.success(request, "La date de livraison a ete ajoutee")
        return redirect("/panier/index_livraison/")
    return form({'panierform': livraison}, 'panier/panier.html', request)

@login_required
@permission_required('bureau')
def edit_livraison(request, livraisonid):
    try:
        livraison_instance = Livraison.objects.get(pk=livraisonid)
    except Livraison.DoesNotExist:
        messages.error(request, u"Entrée inexistante" )
        return redirect("/panier/")
    livraison = LivraisonForm(request.POST or None, instance=livraison_instance)
    if livraison.is_valid():
        with transaction.atomic(), reversion.create_revision():
            livraison.save()
            reversion.set_user(request.user)
            reversion.set_comment("Champs modifié(s) : %s" % ', '.join(field for field in livraison.changed_data))
        messages.success(request, "Date modifiee")
        return redirect("/panier/index_livraison/")
    return form({'panierform': livraison}, 'panier/panier.html', request)

@login_required
@permission_required('bureau')
def del_livraison(request):
    livraison = SelectLivraisonForm(request.POST or None)
    if livraison.is_valid():
        livraison_dels = livraison.cleaned_data['date']
        for livraison_del in livraison_dels:
            try:
                with transaction.atomic(), reversion.create_revision():
                    livraison_del.delete()
                    reversion.set_comment("Destruction")
                messages.success(request, "La date de livraison a ete supprimee")
            except ProtectedError:
                messages.error(
                    request,
                    "La livraison est affectee a au moins une commande, \
                        vous ne pouvez pas le supprimer" % livraison_del)
        return redirect("/panier/index_livraison/")
    return form({'panierform': livraison}, 'panier/panier.html', request)

@login_required
@permission_required('bureau')
def add_paiement(request):
    paiement = PaiementForm(request.POST or None)
    if paiement.is_valid():
        with transaction.atomic(), reversion.create_revision():
            paiement.save()
            reversion.set_user(request.user)
            reversion.set_comment("Creation")
        messages.success(request, "Le moyen de paiement a ete ajoute")
        return redirect("/panier/index_paiement/")
    return form({'panierform': paiement}, 'panier/panier.html', request)

@login_required
@permission_required('bureau')
def edit_paiement(request, paiementid):
    try:
        paiement_instance = Paiement.objects.get(pk=paiementid)
    except Paiement.DoesNotExist:
        messages.error(request, "Entrée inexistante" )
        return redirect("/panier/index_paiement/")
    paiement = PaiementForm(request.POST or None, instance=paiement_instance)
    if paiement.is_valid():
        with transaction.atomic(), reversion.create_revision():
            paiement.save()
            reversion.set_user(request.user)
            reversion.set_comment("Champs modifié(s) : %s" % ', '.join(field for field in paiement.changed_data))
        messages.success(request, "Type de paiement modifié")
        return redirect("/panier/index_paiement/")

panier/templates/panier/aff_paniers.html
{% if management_view %}
<h2>Tableau de bord</h2>

    <table class="table table-striped">
            <tr>
                <th>Solde total des comptes</th>
                <td>{{ solde_total }}</td>
                <th>Solde moyen</th>
                <td>{{ solde_moyen }}</td>
            </tr>
            <tr>
                <th>Nombres de comptes actifs</th>
                <td>{{ user_total }}</td>
                <th>Dont ENS</th>
                <td>{{ user_ens }}</td>
            </tr>
            <tr>
                <th>Nombre total de commandes</th>
                <td>{{ commandes_total }}</td>
                <th>Prochaine livraison</th>
                <td>{{ next_livraison.date }}</td>
            </tr>
            <tr>
                <th>Commandes pour la prochaine livraison</th>
                <td>{{ next_livraison_commandes }}</td>
                <th>Paniers pour la prochaine livraison</th>
                <td>{{ next_livraison_paniers }}</td>
            </tr>
    </table>

{% endif %}

<h2>Commandes</h2>

{% if paniers_list.paginator %}
 <ul class="pagination nav navbar-nav">
    {% if paniers_list.has_previous %}
           <li><a href="?page1=1"> << </a></li>
            <li><a href="?page1={{ paniers_list.previous_page_number }}">Suivants</a></li>
    {% endif %}
    {% for page in paniers_list.paginator.page_range %}
        {% if paniers_list.number <= page|add:"3" and paniers_list.number >= page|add:"-3" %}
        <li class="{% if paniers_list.number == page  %}active{% endif %}"><a href="?page1={{page }}">{{ page }}</a></li>
        {% endif %}
    {% endfor %}

    {% if paniers_list.has_next %}
        <li> <a href="?page1={{ paniers_list.next_page_number }}">Précédents</a></li>
        <li><a href="?page1={{ paniers_list.paginator.page_range|length }}"> >> </a></li>
    {% endif %}
 </ul>
 {% endif %}

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Qualité</th>
                <th>Quantité</th>
                <th>Prix</th>
                <th>Livré</th>
                <th>Date de livraison</th>
                <th>Pas de modification après</th>
                <th></th>
            </tr>
        </thead>
        {% for panier in paniers_list %}
        <tr>
            <td>{{ panier.user.surname }}</td>
            <td>{{ panier.user.name }}</td>
            <td>{{ panier.nom }}</td>
            <td>{{ panier.quantite }}</td>
            <td>{{ panier.prix }}</td>
            {% if panier.livre %}
            <td><font color="green">Oui</font></td>
            {% else %}
            <td><font color="red">Non</font></td>
            {% endif %}
            <td>{{ panier.date.date }}</td>
            <td>{{ panier.date.date_modif }}</td>
            <td><div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="editioncredit" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Editer
            <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="editionfacture">
            <li><a href="{% url 'panier:edit-commande' panier.id %}"><i class="glyphicon glyphicon-bitcoin"></i> Modifier</a></li>
            <li><a href="{% url 'panier:history' 'commande' panier.id %}"><i class="glyphicon glyphicon-repeat"></i> Historique</a></li>
            <li><a href="{% url 'panier:del-commande' panier.id %}"><i class="glyphicon glyphicon-trash"></i> Supprimer</a></li>
            </ul></div></td>
        </tr>
        {% endfor %}
    </table>

<h2>Credits</h2>

 {% if credit_list.paginator %}
 <ul class="pagination nav navbar-nav">
    {% if credit_list.has_previous %}
           <li><a href="?page2=1"> << </a></li>
            <li><a href="?page2={{ credit_list.previous_page_number }}">Suivants</a></li>
    {% endif %}
    {% for page in credit_list.paginator.page_range %}
        {% if credit_list.number <= page|add:"3" and credit_list.number >= page|add:"-3" %}
        <li class="{% if credit_list.number == page  %}active{% endif %}"><a href="?page2={{page }}">{{ page }}</a></li>
        {% endif %}
    {% endfor %}

    {% if credit_list.has_next %}
        <li> <a href="?page2={{ credit_list.next_page_number }}">Précédents</a></li>
        <li><a href="?page2={{ credit_list.paginator.page_range|length }}"> >> </a></li>
    {% endif %}
 </ul>
 {% endif %}

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Montant</th>
                <th>Mode de reglement</th>
                <th>Validité</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        {% for credit in credit_list %}
        <tr>
            <td>{{ credit.user.surname }}</td>
            <td>{{ credit.user.name }}</td>
            <td>{{ credit.montant }}</td>
            <td>{{ credit.moyen }}</td>
            {% if credit.validite %}
            <td><font color="green">Oui</font></td>
            {% else %}
            <td><font color="red">Non</font></td>
            {% endif %}
            {% if is_bureau %}
            <td><div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="editioncredit" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Modifier
            <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="editionfacture">
            <li><a href="{% url 'panier:edit-credit' credit.id %}"><i class="glyphicon glyphicon-bitcoin"></i> Editer</a></li>
            <li><a href="{% url 'panier:del-credit' credit.id %}"><i class="glyphicon glyphicon-trash"></i> Supprimer</a></li>
            </ul></div></td>
            {% endif %}
            <td><a class="btn btn-info btn-sm" role="button" href="{% url 'panier:history' 'credit' credit.id %}"><i class="glyphicon glyphicon-repeat"></i> Historique</a></td> 
        </tr>
        {% endfor %}
    </table>

panier/templates/panier/control.html
{% extends "panier/sidebar.html" %}
{% load bootstrap3 %}
{% load staticfiles%}

{% block title %}Controle des livraisons{% endblock %}

{% block content %}

<form class="form" method="post">
 {% csrf_token %}

{% if livraisonform %}
<h2>Sélectioner une date de livraison</h2>
    <a type="button" class="btn btn-success" href="{% url 'panier:plusProcheLivraison' %}">Livraison la plus proche</a>
    {% bootstrap_form livraisonform %}


{% else %}
<h2>Résumé</h2>
<div class="table-responsive">
    <table class="table table-inverse">
        <tr>
            <th>Commandes pour la livraison</th>
            <td>{{ livraison_commandes }}</td>
            <th>Paniers pour la livraison</th>
            <td>{{ livraison_paniers }}</td>
        </tr>
    </table>
    <table class="table table-inverse">
	    <tr>
            {% for key,value in livraison_quantite.items %}
            <td>{{ key }} panier</td>
            <td><p class="text-success">{{ value }}</p></td>
            {%endfor%}
        </tr>
    </table>
</div>



<h2>Utilisateurs non livrés</h2>
    {{ controlform.management_form }}
<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>  </th>
                <th>Utilisateur</th>
                <th>Solde</th>
                <th>Designation</th>
                <th>Prix unitaire</th>
                <th>Quantite</th>
                <th>Date de livraison</th>
                <th>Livré</th>
                <th>Sac</th>
                <th>Gérer les sacs</th>
                <th></th>
            </tr>
        </thead>
        {% for form in controlform.forms %}
        {% if not form.instance.livre %}
        {% bootstrap_form_errors form %}
        <tr>
            <td><a href="{% url "users:profil" form.instance.user.id%}" class="btn btn-primary btn-sm" role="button"><i class="glyphicon glyphicon-user"></i></a>

            <td>{{ form.instance.user }}</td>
            {% if form.instance.user.solde <= 0 %}
                <td><font color="red">{{ form.instance.user.solde }}</td>   
            {% endif %}
            {% if form.instance.user.solde > 0 and form.instance.user.solde <= form.instance.prix_unitaire %}
                <td><font color="orange">{{ form.instance.user.solde }}</td>   
            {% endif %}
            {% if form.instance.user.solde > form.instance.prix_unitaire %}
                <td><font color="green">{{ form.instance.user.solde }}</td>   
            {% endif %}
            <td>{{ form.instance.nom }}</td>
            <td>{{ form.instance.prix_unitaire }}</td>
            <td>{{ form.instance.quantite }}</td>
            <td>{{ form.instance.date }}</td>
            <td>{{ form.livre }}</td>
	    <td>{{ form.instance.user.sac_consignes }}</td>
            <td><a class="btn btn-primary btn-sm" role="button" href="{% url 'panier:add-sac' form.instance.user.id %}"><i class="glyphicon glyphicon-plus"></i> Ajouter</a></td>
            <td> <a class="btn btn-primary btn-sm" role="button" href="{% url 'panier:del-sac' form.instance.user.id %}"><i class="glyphicon glyphicon-minus"></i> Retirer</a></td>
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
        </tr>
        {% endif %}
        {% endfor %}
    </table>
</div>

<h2>Utilisateurs déjà livrés</h2>
    {{ controlform.management_form }}
<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>  </th>
                <th>Utilisateur</th>
                <th>Designation</th>
                <th>Prix unitaire</th>
                <th>Quantite</th>
                <th>Date de livraison</th>
                <th>Livré</th>
                <th>Sac consignés</th>
                <th>Gérer les sacs</th>
                <th></th>
            </tr>
        </thead>
        {% for form in controlform.forms %}
        {% if form.instance.livre %}
        {% bootstrap_form_errors form %}
        <tr>
            <td><a href="{% url "users:profil" form.instance.user.id%}" class="btn btn-primary btn-sm" role="button"><i class="glyphicon glyphicon-user"></i></a>
            <td>{{ form.instance.user }}</td>
            <td>{{ form.instance.nom }}</td>
            <td>{{ form.instance.prix_unitaire }}</td>
            <td>{{ form.instance.quantite }}</td>
            <td>{{ form.instance.date }}</td>
            <td>{{ form.livre }}</td>
        <td>{{ form.instance.user.sac_consignes }}</td>
            <td><a class="btn btn-primary btn-sm" role="button" href="{% url 'panier:add-sac' form.instance.user.id %}"><i class="glyphicon glyphicon-plus"></i> Ajouter</a></td>
            <td> <a class="btn btn-primary btn-sm" role="button" href="{% url 'panier:del-sac' form.instance.user.id %}"><i class="glyphicon glyphicon-minus"></i> Retirer</a></td>
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
        </tr>
        {% endif %}
        {% endfor %}
    </table>
</div>

{% endif %}
{% bootstrap_button "Valider" button_type="submit"  icon="star" %}


</form>

{% endblock %}

panier/templates/panier/delete.html
{% extends "panier/sidebar.html" %}
{% load bootstrap3 %}

{% block title %}Création et modificatio nde commandes et de credits {% endblock %}

{% block content %}

<form class="form" method="post">
    {% csrf_token %}
    <h4>Attention, voulez-vous vraiment supprimer cet objet {{ objet_name }} ( {{ objet }} ) ?</h4>
    {% bootstrap_button "Confirmer" button_type="submit" icon="trash" %}
</form>
  <br />
  <br />
  <br />
{% endblock %}

panier/templates/panier/sidebar.html
{% extends "base.html" %}

{% block sidebar %}
    <a class="list-group-item list-group-item-info" href="{% url "panier:index-livraison" %}">
        <i class="glyphicon glyphicon-list"></i>
        Liste des dates de livraison
    </a>
    <a class="list-group-item list-group-item-info" href="{% url "panier:index-article" %}">
        <i class="glyphicon glyphicon-list"></i>
        Articles en vente
    </a>
    {% if is_bureau %}
    <a class="list-group-item list-group-item-info" href="{% url "panier:index-paiement" %}">
        <i class="glyphicon glyphicon-list"></i>
        Liste des moyens de paiement
    </a>
    <a class="list-group-item list-group-item-warning" href="{% url "panier:control" %}">
        <i class="glyphicon glyphicon-eye-open"></i>
        Etat des livraisons
    </a>
    {% endif %}
{% endblock %}